name = "Colorfy"
uuid = "03fe91ce-8ec6-4610-8e8d-e7491ccca690"
authors = ["Elias Carvalho <eliascarvdev@gmail.com> and contributors"]
version = "1.2.0"

[deps]
ColorSchemes = "35d6a980-a343-548e-a6ea-1d62b119f2f4"
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
FixedPointNumbers = "53c48c17-4a7d-5ca2-90c5-79b7896eea93"

[weakdeps]
CategoricalArrays = "324d7699-5711-5eae-9e2f-1d82baa6b597"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"

[extensions]
ColorfyCategoricalArraysExt = "CategoricalArrays"
ColorfyDistributionsExt = "Distributions"
ColorfyUnitfulExt = "Unitful"

[compat]
CategoricalArrays = "1.0"
ColorSchemes = "3.24"
Colors = "0.12, 0.13"
Dates = "1.10"
Distributions = "0.25"
FixedPointNumbers = "0.8"
Unitful = "1.19"
julia = "1.10"
